###
# Get all Accounts
GET http://localhost:3000/account
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWJiY2IzMDE4MmI0ZjljODkxYzQwNzMiLCJpYXQiOjE3MDY4ODU0NTUsImV4cCI6MTcwNjg4OTA1NX0.aszaATR9mSfR9XBF-DuNNR4hwrJFc28tHp5OIoDLh_U

###
# Get Account by name
GET http://localhost:3000/account?name=test
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWJhNjBiMjE5ZTQwNjgwNjgwM2FiYTgiLCJpYXQiOjE3MDY3MTUyODgsImV4cCI6MTcwNjcxODg4OH0.cuCmj1TduHBNpCYIIksCoVNCqKLaY0UwSqwn3m3wp6o

###
#Get Account by ID
GET http://localhost:3000/account/65bfa7d5773157f838ea7596
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWJmYTdkNTc3MzE1N2Y4MzhlYTc1OTYiLCJpYXQiOjE3MDcwNTkyMzQsImV4cCI6MTcwNzA2MjgzNH0.Oh_jY6IBCID7H2XcJrnlLfOxLizrSdp1TX0rZ8bhMQU

###
#Update Account by ID
PUT http://localhost:3000/account/65ba69a2112667c460adf5d3
Content-Type: application/json
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWJhNjBiMjE5ZTQwNjgwNjgwM2FiYTgiLCJpYXQiOjE3MDY3MTUzNTAsImV4cCI6MTcwNjcxODk1MH0.ybjdWKvkRuJIK7GMFXFNWhr3leaRcxCDJFv5e91fcck

{
  "name": "david",
  "email":"david@gmail.com"
}

###
#Delete Account by ID
DELETE http://localhost:3000/account/65ba69a2112667c460adf5d3
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWJhNjBiMjE5ZTQwNjgwNjgwM2FiYTgiLCJpYXQiOjE3MDY3MTUzNTAsImV4cCI6MTcwNjcxODk1MH0.ybjdWKvkRuJIK7GMFXFNWhr3leaRcxCDJFv5e91fcck

###
# Get All posts of Account by id
GET http://localhost:3000/account/posts/65bea035107daf40e969cdf3
Content-Type: application/json
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWJlYTAzNTEwN2RhZjQwZTk2OWNkZjMiLCJpYXQiOjE3MDY5OTE2ODgsImV4cCI6MTcwNjk5NTI4OH0.foGqrt-tM4vzb_wRmxEnsiGaRgzpou-2MGthbeLydRE

###
#Register Account
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "email": "omer@walla.com",
  "password": "1234",
  "name": "omer"
}

###
# Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "omer@walla.com",
  "password": "1234",
  "name": "omer"
}

###
# Logout
POST http://localhost:3000/auth/logout
Content-Type: application/json
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWJiZDcyN2FmMTM5ZTM0MGI1YThjNzQiLCJpYXQiOjE3MDY4MTI4NjB9.NfRToukR31KsgN1uZ_F51ESZqZ66PDeKhXLFYMQgjhY

###
# Refresh Token
GET  http://localhost:3000/auth/refresh
Content-Type: application/json
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWJiZDcyN2FmMTM5ZTM0MGI1YThjNzQiLCJpYXQiOjE3MDY4MTI4MTF9.rTLf6KuPCKwCamZvXeW2xtToRcb7IzCkSz7CePyhe5w



