###

GET http://localhost:3000/user

###

GET http://localhost:3000/user/123123

###

GET http://localhost:3000/user/123123

###

POST http://localhost:3000/user 
Content-Type: application/json

{
    "name": "hjkg ",
    "_id": "123123"
}

###
POST http://localhost:3000/userpost
Content-Type: application/json

{
    "title": "test1",
    "message": "message1",
    "owner": "1234567"
}
###
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "email": "dor",
    "password": "1222"
}
###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "dor",
    "password": "1222"
}
###
POST http://localhost:3000/auth/logout
Content-Type: application/json

{
    "email": "dor",
    "password": "1222"
}