###

GET http://localhost:3000/user
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWI2YThjY2I4NmM5ZGFkM2NjNWZlNzEiLCJpYXQiOjE3MDY0Njk2MDQsImV4cCI6MTcwNjQ3MzIwNH0.2f03xf5FgHwLKUwqnQNyuWaXehfg2-zzuKIjtUWWk8E
###

GET http://localhost:3000/user?name=John%20Doe

###

GET http://localhost:3000/user/1234567891

###

POST http://localhost:3000/user 
Content-Type: application/json

{
"name": "abc", "_id": "1234567891"
}

###

PUT http://localhost:3000/user/1234567890
Content-Type: application/json

{
"name": "John Doe 1", "_id": "1234567890"
}
###
POST http://localhost:3000/auth/register 
Content-Type: application/json

{
"email": "test1212321@test.com", "password": "12345678901"
}

###

POST http://localhost:3000/auth/login
Content-Type: application/json

{
"email": "test1212321@test.com", "password": "12345678901"
}