# Create comment
POST http://localhost:3000/comment/65be6b218a3b4bdfdba0f753
Content-Type: application/json
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWJlNmJiNmRhZDUzYWYyN2NmZTg4NjUiLCJpYXQiOjE3MDY5NzgyMzgsImV4cCI6MTcwNjk4MTgzOH0.ijhcnIW3KU-VnKZQvM9p5Zk4FStwrEkRBgiYM4cKyX4


{
  "content": "This is a comment2"
}