###
# Get all Posts
GET http://localhost:3000/userpost

###
# Get Post by ID
GET http://localhost:3000/userpost/65bd04c2f86e6d3ce603925e
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWJiY2IzMDE4MmI0ZjljODkxYzQwNzMiLCJpYXQiOjE3MDY4ODU0NTUsImV4cCI6MTcwNjg4OTA1NX0.aszaATR9mSfR9XBF-DuNNR4hwrJFc28tHp5OIoDLh_U

###
#Create Post
POST http://localhost:3000/userpost
Content-Type: application/json
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWJiZDcyN2FmMTM5ZTM0MGI1YThjNzQiLCJpYXQiOjE3MDY4ODYzMzEsImV4cCI6MTcwNjg4OTkzMX0.JsHriUFs4eDwjOGfRXz61-akO4iXN_Gi0crzPHnrpDw

{
  "title": "title",
  "message": "message"
}

###
#Update Post
PUT http://localhost:3000/userpost/65ba6ac8112667c460adf5df
Content-Type: application/json
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWJiZDcyN2FmMTM5ZTM0MGI1YThjNzQiLCJpYXQiOjE3MDY4MDkxMzMsImV4cCI6MTcwNjgxMjczM30.1p6_V1i4gjW8zZLuVZAxgLgzzV_F1pjHdnPD1sLkbnY

{
  "title": "hello",
  "message": "world"
}

###
# Delete Post
DELETE http://localhost:3000/userpost/65ba6ac8112667c460adf5df
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWJhNjlhMjExMjY2N2M0NjBhZGY1ZDMiLCJpYXQiOjE3MDY3MTYxODksImV4cCI6MTcwNjcxOTc4OX0.SV08KoUH6C6L5khX0H7TJOVygjgiGFZgPdgNSU_RWzc



###
# Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "1234",
  "name": "test"
}